/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import javax.swing.JTable;
import controller.*;
import Model.*;
import javax.swing.JButton;
import javax.swing.JTextField;


/**
 *
 * @author Lab Informatika
 */
public class mainview extends javax.swing.JFrame {

    /**
     * Creates new form mainview
     */
    controllerGym data;
    public mainview() {
        initComponents();
        data = new controllerGym(this);
        data.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelGym = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Falat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fnomor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Fwaktu = new javax.swing.JTextField();
        Btambah = new javax.swing.JButton();
        Bclear = new javax.swing.JButton();
        Bubah = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelGym.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Pemilik", "Nama Alat", "Nomor Telepon", "Waktu Sewa", "Biaya Sewa"
            }
        ));
        jScrollPane1.setViewportView(TabelGym);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BullKing Gym");

        jLabel2.setText("Nama Penyewa");

        Fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Alat");

        Falat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalatActionPerformed(evt);
            }
        });

        jLabel4.setText("Nomor Telepon");

        Fnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnomorActionPerformed(evt);
            }
        });

        jLabel5.setText("Waktu Sewa (Hari)");

        Fwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FwaktuActionPerformed(evt);
            }
        });

        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });

        Bclear.setText("Clear");

        Bubah.setText("Ubah");

        Bhapus.setText("Hapus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fnama)
                    .addComponent(Falat)
                    .addComponent(Fnomor)
                    .addComponent(Fwaktu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btambah)
                            .addComponent(Bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(Bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Falat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btambah)
                            .addComponent(Bubah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bclear)
                            .addComponent(Bhapus))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnamaActionPerformed

    private void FalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FalatActionPerformed

    private void FnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnomorActionPerformed

    private void FwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FwaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FwaktuActionPerformed

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclear;
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Btambah;
    private javax.swing.JButton Bubah;
    private javax.swing.JTextField Falat;
    private javax.swing.JTextField Fnama;
    private javax.swing.JTextField Fnomor;
    private javax.swing.JTextField Fwaktu;
    private javax.swing.JTable TabelGym;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelGym() {
        return TabelGym;
    }

    public void setTabelGym(JTable TabelGym) {
        this.TabelGym = TabelGym;
    }

    public controllerGym getData() {
        return data;
    }

    public void setData(controllerGym data) {
        this.data = data;
    }

    public JButton getBclear() {
        return Bclear;
    }

    public void setBclear(JButton Bclear) {
        this.Bclear = Bclear;
    }

    public JButton getBhapus() {
        return Bhapus;
    }

    public void setBhapus(JButton Bhapus) {
        this.Bhapus = Bhapus;
    }

    public JButton getBtambah() {
        return Btambah;
    }

    public void setBtambah(JButton Btambah) {
        this.Btambah = Btambah;
    }

    public JButton getBubah() {
        return Bubah;
    }

    public void setBubah(JButton Bubah) {
        this.Bubah = Bubah;
    }

    public JTextField getFalat() {
        return Falat;
    }

    public void setFalat(JTextField Falat) {
        this.Falat = Falat;
    }

    public JTextField getFnomor() {
        return Fnomor;
    }

    public void setFnomor(JTextField Fnomor) {
        this.Fnomor = Fnomor;
    }

    public JTextField getFwaktu() {
        return Fwaktu;
    }

    public void setFwaktu(JTextField Fwaktu) {
        this.Fwaktu = Fwaktu;
    }

}
